# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build toolchain using kaniko
        uses: DCNick3/action-kaniko-rootfs@master
        with:
          cache: true
          cache_registry: cache
          password: ${{ secrets.GITHUB_TOKEN }}
          rootfs_path: "toolchain-real.tar.gz"
        
      - name: Create a Release
        uses: elgohr/Github-Release-Action@d2946e240e320230d1811f35b8ff71545eb5d458
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: ${{ github.sha }}
        
          
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "toolchain-real.tar.gz"
